### ISSUE TITLE
Issue with Flic Button Setup

### ISSUE THREAD

**Issue by virginiafarmer** [Djelibeybi/homebridge-button-platform#46]
Hey thanks in advance for your help! I'm new to homebridge so this may be a rookie mistake...

I previously had my flic buttons set up and working via Homebridge but it suddenly stopped working. I just set up static IP addresses but am still getting some errors.

In this example I have a flic button called "nurseryflic) and I've got the Flic app set up with settings:
Type: Post
URL: http://192.168.68.105:3001/button-nurseryflic
Content Type: application/x-www-form-urlencoded

For a single click it works great but for a double and hold action I get the error "Internet Request: Request failed: internal server error 500". Any chance anyone is familiar with that error?  Thanks!

Here is the log created in Homebridge.
```
[5/20/2021, 11:04:43 AM] [Flic Buttons] Received POST request on /button-nurseryflic to trigger a [double-click] event for Nurseryflic
TypeError: accessory.switchService.triggerEvent.triggerEvent is not a function
    at /usr/local/lib/node_modules/homebridge-button-platform/lib/ButtonPlatform.js:155:50
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-button-platform/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/homebridge-button-platform/node_modules/express/lib/router/route.js:137:13)
    at middleware (/usr/local/lib/node_modules/homebridge-button-platform/node_modules/express-validator/src/middlewares/one-of.js:36:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Djelibeybi** [comment]
Thanks for reporting this, I'll take a look to see if I can reproduce this.

**Comment by Djelibeybi** [comment]
I've just released v1.4.2 which should fix this bug. Thanks for reporting it!

**Comment by virginiafarmer** [comment]
Nice that looks like it worked. Thanks so much for looking into it!

**Comment by Djelibeybi** [comment]
You're welcome. I should also point out that it's probably easier to configure a URL with a query in the Flic interface, i.e. `http://homebridge:3001/button-nurseryflic?event=click` instead of having to change the Content-Type or add a Body.
